# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  displayName: 'Install Entity Framework CLI'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" tool install --global dotnet-ef'

- task: CmdLine@2
  displayName: 'EF Migration script Configuration Context'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" ef migrations script -c ConfigurationDbContext  -o %BUILD_ARTIFACTSTAGINGDIRECTORY%\ConfigurationDbMigration.sql --startup-project ../../Services/Authorization.IdentityServer --verbose'
    workingDirectory: 'src/Data/Authorization'

- task: CmdLine@2
  displayName: 'EF Migration script Persisted Grant'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" ef migrations script -c PersistedGrantDbContext  -o %BUILD_ARTIFACTSTAGINGDIRECTORY%\PersistedGrantDbMigration.sql --startup-project ../../Services/Authorization.IdentityServer --verbose'
    workingDirectory: 'src/Data/Authorization'

- task: CmdLine@2
  displayName: 'EF Migration script Identity Server'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" ef migrations script -c IdentityServerDbContext  -o %BUILD_ARTIFACTSTAGINGDIRECTORY%\IdentityServerDbMigration.sql --startup-project ../../Services/Authorization.IdentityServer --verbose'
    workingDirectory: 'src/Data/Authorization'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--runtime linux-x64'
    projects: 'src/Services/Authorization.IdentityServer'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    projects: 'src/Services/Authorization.IdentityServer'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'IdentityServer'
    publishLocation: 'Container'
