# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  displayName: 'Install Entity Framework CLI'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" tool install --global dotnet-ef'

- task: CmdLine@2
  displayName: 'EF Migration script'
  inputs:
    script: '"C:\Program Files\dotnet\dotnet.exe" ef migrations script -c TimeTrackingDbContext  -o %BUILD_ARTIFACTSTAGINGDIRECTORY%\migrate.sql --startup-project ../../Services/TimeTracking.Api --verbose'
    workingDirectory: 'src/Data/TimeTracking'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/Services/TimeTracking.Api'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    projects: 'src/Services/TimeTracking.Api'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'TimeTrackingAPI'
    publishLocation: 'Container'